# Generated by Django 4.2.6 on 2023-11-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="first_name",
            field=models.CharField(default="fname", max_length=50),
        ),
        migrations.AddField(
            model_name="details",
            name="last_name",
            field=models.CharField(default="lname", max_length=50),
        ),
    ]
