# Generated by Django 4.2.6 on 2023-11-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_details_first_name_details_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="details",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="details",
            name="last_name",
        ),
    ]
