# Generated by Django 4.2.6 on 2023-11-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_details_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="role",
            field=models.CharField(default="regular", max_length=10),
        ),
    ]
