# Generated by Django 4.2.6 on 2023-10-25 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0003_category_access_category_cancel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="author",
            field=models.CharField(default="Pranav"),
        ),
        migrations.AddField(
            model_name="item",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
