# Generated by Django 4.2.6 on 2023-10-25 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0004_item_author_item_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
