# Generated by Django 4.2.6 on 2023-11-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0005_alter_category_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
