# Generated by Django 4.2.6 on 2023-11-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0007_alter_category_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
