# Generated by Django 4.2.6 on 2023-11-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0008_alter_category_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="inclusions",
            field=models.TextField(
                default="Hard-to-Get-to Places, To & Fro Pickup and Drop, Breakfast Buffet"
            ),
        ),
    ]
