# Generated by Django 4.2.6 on 2023-11-13 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0010_alter_category_inclusions"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tripobeatApp.category",
            ),
        ),
    ]
