# Generated by Django 4.2.6 on 2023-11-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0011_review_date_posted_review_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                default=66,
                on_delete=django.db.models.deletion.CASCADE,
                to="tripobeatApp.category",
            ),
        ),
    ]
