# Generated by Django 4.2.6 on 2023-11-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripobeatApp", "0012_alter_review_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tripobeatApp.category",
            ),
        ),
    ]
